### ISSUE TITLE
求实现好友图片保存选项:)

### ISSUE THREAD

**Issue by wxg4net** [sjdy521/Webqq-Client#3]
我今天看了下w.qq接受图片的选项。接受图片时，增加了 file_path=‘/fb911482-a8e2-4eef-ba9a-825bb362fccb’ 图片路径。
然后访问 http://w.qq.com/d/channel/get_offpic2?file_path=%2Ffb911482-a8e2-4eef-ba9a-825bb362fccb&f_uin=xxxxxxxx&clientid=xxxx&psessionid=xxxx 获得一个302转向 真实图片路径(无需cookie 浏览器可以直接访问)。不过我实现起来稍微困难。求 灰灰同学 支持。

**Comment by sjdy521** [comment]
smartqq只会对好友发送的图片"offpic" 类型 进行下载，其他类型的图片消息“cface” 只会显示成文字："[自定义表情]"

this.translateMessage = function(p) {
            for (var y = p.content,
            F = p.from_uin,
            H = !F || F == mq.model.buddylist.getSelfUin(), M = [], P = 0, E; E = y[P]; P++) if (g.type.isArray(E)) switch (E[0]) {
            case "font":
                break;
            case "face":
                E = z.indexOf(E[1]);
                M.push('<img class="EQQ_faceImg" src="http://pub.idqqimg.com/lib/qqface/' + B[E] + '.gif" width="24px" height="24px">');
                break;
            case "cface":
                M.push("[\u81ea\u5b9a\u4e49\u8868\u60c5]");
                break;
            case "offpic":
                M.push('<img rdata="offpic" src="/css/image/img_loading.gif" _ori_src="http://w.qq.com/d/channel/get_offpic2?file_path=' + encodeURIComponent(E[1].file_path) + "&f_uin=" + F + "&clientid=" + mq.clientid + "&psessionid=" + mq.psessionid + '" title="\u81ea\u5b9a\u4e49\u8868\u60c5\u56fe\u7247" style="max-width:100%" />');
                break;
            case "sendfile":
                M.push('<span class="icon icon_info"></span>\u60a8\u53d1\u9001\u6587\u4ef6"' + b.encodeHtml(E[1]) + '"\u7ed9\u5bf9\u65b9\u3002');
                break;

**Comment by wxg4net** [comment]
好友已足矣...

**Comment by wxg4net** [comment]
我的想法是这样的：
目的：好友收到包含图片的消息后，能把“图片url”显示给前台。这样通过访问此url即可查看图片
解释：图片URL 即 通过file_path, clientid, psessionid与f_uin参数 组合生成的url(http://w.qq.com/d/channel/get_offpic2............)访问。返回的response中的 header location转向地址。
优点：无需保存
缺陷： 虽然我测试时，可以直接访问获取图片。这个图片URL地址估计有一定的有效性。但影响不打。

高级点实现就是 你说的实现一个回调函数 参数需要 保存的路径。然后后台给下载下来。然后把这个保存后完整地址发送给前台(STDOUT)... 请参考....

**Comment by sjdy521** [comment]
现在我设计的形式就是添加一个回调，会先把图片下载到本地，在回调中会把图片本地路径作为参数

发自我的 iPhone

**Comment by wxg4net** [comment]
已测试 修复change错误和禁止tmp自动删除 https://github.com/wxg4net/Webqq-Client/commit/29c998252acf9598cf3bd82891e86c3cfa928320
